version: '3.4'

services:
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
    ports:
        - 5001:443

  indentity.db:
    image: postgres
    container_name: identity.db
    environment:
        - POSTGRES_DB=identity
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - 5432:5432
